
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.22621 - AMD64
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/cmake/share/cmake-3.26/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/cmake/share/cmake-3.26/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/cmake/share/cmake-3.26/Modules/CheckCCompilerFlag.cmake:40 (cmake_check_compiler_flag)"
      - "build_web/_deps/raylib-src/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "build_web/_deps/raylib-src/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "build_web/_deps/raylib-src/CMakeLists.txt:29 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "F:/myfirstgame/build_web/CMakeFiles/CMakeScratch/TryCompile-yc5vp2"
      binary: "F:/myfirstgame/build_web/CMakeFiles/CMakeScratch/TryCompile-yc5vp2"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_MODULE_PATH: "F:/myfirstgame/build_web/_deps/raylib-src/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: F:/myfirstgame/build_web/CMakeFiles/CMakeScratch/TryCompile-yc5vp2
        
        Run Build Command(s):C:/cmake/bin/cmake.exe -E env VERBOSE=1 C:/MinGW/bin/mingw32-make.exe -f Makefile cmTC_75532/fast && C:/MinGW/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_75532.dir\\build.make CMakeFiles/cmTC_75532.dir/build
        mingw32-make.exe[1]: Entering directory 'F:/myfirstgame/build_web/CMakeFiles/CMakeScratch/TryCompile-yc5vp2'
        Building C object CMakeFiles/cmTC_75532.dir/src.c.o
        C:\\emsdk\\upstream\\emscripten\\emcc.bat -DCOMPILER_HAS_THOSE_TOGGLES  -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_75532.dir/src.c.o -MF CMakeFiles\\cmTC_75532.dir\\src.c.o.d -o CMakeFiles\\cmTC_75532.dir\\src.c.o -c F:\\myfirstgame\\build_web\\CMakeFiles\\CMakeScratch\\TryCompile-yc5vp2\\src.c
        Linking C executable cmTC_75532.js
        C:\\cmake\\bin\\cmake.exe -E cmake_link_script CMakeFiles\\cmTC_75532.dir\\link.txt --verbose=1
        C:\\emsdk\\upstream\\emscripten\\emcc.bat @CMakeFiles\\cmTC_75532.dir\\objects1.rsp -o cmTC_75532.js 
        cache:INFO: generating system asset: symbol_lists/7a974f7065b03f039b58c3afd6b04fb646712f63.json... (this will be cached in "C:\\emsdk\\upstream\\emscripten\\cache\\symbol_lists\\7a974f7065b03f039b58c3afd6b04fb646712f63.json" for subsequent builds)
        cache:INFO:  - ok
        cache:INFO: generating system library: sysroot\\lib\\wasm32-emscripten\\libstubs-debug.a... (this will be cached in "C:\\emsdk\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten\\libstubs-debug.a" for subsequent builds)
        system_libs:INFO: compiled 2 inputs
        cache:INFO:  - ok
        cache:INFO: generating system library: sysroot\\lib\\wasm32-emscripten\\libc-debug.a... (this will be cached in "C:\\emsdk\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten\\libc-debug.a" for subsequent builds)
        system_libs:INFO: compiled 1023 inputs
        cache:INFO:  - ok
        cache:INFO: generating system library: sysroot\\lib\\wasm32-emscripten\\libc++abi-debug-noexcept.a... (this will be cached in "C:\\emsdk\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten\\libc++abi-debug-noexcept.a" for subsequent builds)
        system_libs:INFO: compiled 16 inputs
        cache:INFO:  - ok
        mingw32-make.exe[1]: Leaving directory 'F:/myfirstgame/build_web/CMakeFiles/CMakeScratch/TryCompile-yc5vp2'
        
      exitCode: 0
...
